export default {
    // PORTS
    SERVER_HOST: 'http://localhost',
    SERVER_PORT: 8000,

    // SOCKET MESSAGES
    LOGIN: 'LOGIN',
    SEARCH_USERS: 'SEARCH_USERS',
    DISPLAY_NAME: 'DISPLAY_NAME',
    USERS: 'USERS',
    CREATE_ROOM: 'CREATE_ROOM',
    CREATE_ROOM_SUCCESS: 'CREATE_ROOM_SUCCESS',
    CONNECT_TO_ROOM: 'CONNECT_TO_ROOM',
    ROOM_STATUS: 'ROOM_STATUS',
    SEND_ROOM_INVITES: 'SEND_ROOM_INVITES',
    REJECT_TRANSFER_REQUEST: 'REJECT_TRANSFER_REQUEST',
    ACCEPT_TRANSFER_REQUEST: 'ACCEPT_TRANSFER_REQUEST',

    // SOCKET MESSAGES DATA
    USER_CONNECT: 'USER_CONNECT',
    USER_DISCONNECT: 'USER_DISCONNECT',

    // RTC SOCKET MESSAGES
    ICE_CANDIDATE: 'ICE_CANDIDATE',
    RTC_DESCRIPTION_OFFER: 'RTC_DESCRIPTION_OFFER',
    RTC_DESCRIPTION_ANSWER: 'RTC_DESCRIPTION_ANSWER',

    // FILE TRANSFER RTC SOCKET MESSAGES
    FILE_TRANSFER_REQUEST: 'FILE_INFO_REQUEST',
    FILE_TRANSFER_REPLY: 'FILE_TRANSFER_REPLY',
    FILE_ACCEPT: 'FILE_ACCEPT',
    FILE_REJECT: 'FILE_REJECT',
};
