export default {
    // PORTS
    SERVER_HOST: 'http://localhost',
    SERVER_PORT: 8000,

    // USER AUTH STATES
    LOGIN: 'LOGIN',
    SIGN_UP: 'SIGN_UP',

    // SOCKET MESSAGES
    CREATE_ROOM: 'CREATE_ROOM',
    CREATE_ROOM_SUCCESS: 'CREATE_ROOM_SUCCESS',
    CONNECT_TO_ROOM: 'CONNECT_TO_ROOM',
    CONNECT_TO_ROOM_FAIL: 'CONNECT_TO_ROOM_FAIL',
    USERS_CONNECTED: 'USERS_CONNECTED',
    ROOM_FULLY_CONNECTED: 'ROOM_FULLY_CONNECTED',
};
